<div class="widget-banner<?php if ( $this->getCssClass() ): ?> <?php echo $this->getCssClass(); ?><?php endif; ?>">
	<a class="widget-cell" href="<?php echo $this->getWidgetUrl(); ?>">
		<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $this->getImage(); ?>" alt=""/>
		<?php if ($this->hasTitle()): ?><span class="title"><?php echo $this->getTitle(); ?></span><?php endif; ?>
		<?php if ($this->hasDescription()): ?><span class="description"><?php echo $this->getDescription(); ?></span><?php endif; ?>
	</a>
</div>