<div class="links footer-social-links">
	<div class="block-title"><?php echo Mage::getStoreConfig( 'boilareplate/social_links/title' ); ?></div>
	<ul>
		<li>
			<a title="<?php echo $this->__("facebook"); ?>" title="" target="_blank" href="<?php echo Mage::getStoreConfig( 'boilareplate/social_links/facebook' ) ?>">
				<i class="icon-facebook"></i>
			</a>
		</li>
		<li>
			<a title="<?php echo $this->__("instagram"); ?>" target="_blank" href="<?php echo Mage::getStoreConfig( 'boilareplate/social_links/instagram' ) ?>">
				<i class="icon-instagram"></i>
			</a>
		</li>
		<li>
			<a title="<?php echo $this->__("pinterest"); ?>" target="_blank" href="<?php echo Mage::getStoreConfig( 'boilareplate/social_links/pinterest' ) ?>">
				<i class="icon-pinterest"></i>
			</a>
		</li>
	</ul>
</div>