<div class="footer-social-links">
	<h4><?php echo Mage::getStoreConfig( 'boilareplate/social_links/title' ); ?></h4>
	<ul>
		<li><a title="facebook" target="_blank"
		       href="<?php echo Mage::getStoreConfig( 'boilareplate/social_links/facebook' ) ?>"><i
					class="icon-facebook"></i></a></li>
		<li><a title="instagram" target="_blank"
		       href="<?php echo Mage::getStoreConfig( 'boilareplate/social_links/instagram' ) ?>"><i
					class="icon-instagram-filled"></i></a></li>
	</ul>
</div>