<div class="home-container container">
	<div class="row">
		<div class="col-sm-7">
			<div class="home-instagram-gallery home-gallery">
				<h3 class="gallery-title"><?php echo Mage::getStoreConfig( 'boilareplate/instagram/title' ) ?></h3>
				<h5 class="gallery-subtitle"><?php echo Mage::getStoreConfig( 'boilareplate/instagram/subtitle' ) ?></h5>
				<?php echo $this->getChildHtml( 'home.instagram' ); ?>
			</div>
		</div>
		<div class="col-sm-5">
			<div class="home-celebs-gallery home-gallery">
				<h3 class="gallery-title"><?php echo Mage::getStoreConfig( 'boilareplate/celebs/title' ) ?></h3>
				<h5 class="gallery-subtitle"><?php echo Mage::getStoreConfig( 'boilareplate/celebs/subtitle' ) ?></h5>
				<?php echo $this->getChildHtml( 'home.celebs' ); ?>
			</div>
		</div>
	</div>
</div>