<div
	class="widget-product-carousel<?php if ( $this->getCssClass() ): ?> <?php echo $this->getCssClass(); ?><?php endif; ?>">
	<div class="widget-title"><?php echo $this->getTitle(); ?></div>
	<?php if ( $_subtitle = $this->getSubtitle() ): ?>
		<div class="widget-subtitle"><?php echo $this->getSubtitle(); ?></div>
	<?php endif; ?>

		<?php if (( $_products = $this->getProductCollection() ) && $_products->getSize()): ?>
		<div class="widget-products slideshow" id="<?php echo $this->getId(); ?>" data-cycle-pager-template="<div class=page></div>">
			<?php $i = 0; ?>
			<?php foreach ( $_products->getItems() as $_product ): ?>
				<div class="item slide">
					<div class="slide-inner">
						<?php // The image size is locked at 210 for this for display purposes. CSS has it at 75% which should equate to 278px?>
						<a href="<?php echo $_product->getProductUrl() ?>"
						   title="<?php echo $this->stripTags( $_product->getName(), null, true ) ?>"
						   class="product-image">
							<img
								src="<?php echo $this->helper( 'catalog/image' )->init( $_product, 'small_image' )->keepFrame( false )->resize( $this->getImageWidth(),$this->getImageHeight() ) ?>"
								alt="<?php echo $this->stripTags( $_product->getName(), null, true ) ?>"/>
						</a>

						<div class="product-info">
							<h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
							                            title="<?php echo $this->stripTags( $_product->getName(), null, true ) ?>)"><?php echo $this->helper( 'catalog/output' )->productAttribute( $_product, $_product->getName(), 'name' ) ?></a>
							</h3>
							<?php echo $this->getPriceHtml( $_product, true, '-widget-carousel-grid' ) ?>
						</div>
					</div>
				</div>
			<?php endforeach; ?>
		</div>

	<script>
		//<![CDATA[
		(function ($) {

			var cycleOptions = {
				timeout: <?php echo $this->getTimeout() ?>,
				speed: <?php echo $this->getSpeed() ?>,
				slides: '.slide',
				paused: <?php echo $this->getPaused() ? 1 : 0; ?>,
				reverse: 0,
				pauseOnHover: true,
				showArrows: <?php echo $this->getShowNavs() ? 1 : 0; ?>,
				showPager: <?php echo $this->getShowPager() ? 1 : 0; ?>,
				fx: 'carousel',
				carouselFluid: true,
				allowWrap: 1,
				carouselVisible: <?php echo $this->getProductsPerPage() ?>,
				autoHeight: 1
			};

			$('#<?php echo $this->getId(); ?>').cycleEvents().cycle(cycleOptions);

		})(jQuery);
		//]]>
	</script>
<?php else: ?>
	<?php echo $this->__( "There are no products matching the selection." ); ?>
<?php endif; ?>

</div>

